#!/usr/bin/env node
// Builds the character lists of L-13 check ④ (doc 06 §4.3, R64, I18-06/07) from the vendored OpenCC table:
//   src/data/glossary/_simplified-only.txt     zh-Hant: characters that only exist as simplified forms
//   src/data/glossary/_simplified-only-ja.txt  ja: the same minus every kanji of JIS X 0208 (levels 1 and 2, which hold
//                                               the Jōyō kanji), so that 国 or 図 stay legal in Japanese copy
// A character is simplified-only when it is a key of STCharacters.txt and no line lists it as a traditional form.
// JIS X 0208 comes from the platform's EUC-JP decoder (WHATWG Encoding, full ICU), so nothing else is downloaded.
//
// Source: scripts/vendor/opencc/STCharacters.txt (Apache-2.0, see scripts/vendor/opencc/LICENSE and README.md).
// Run after updating the vendored file: node scripts/simplified-chars.mjs   (zero dependencies, Node ≥ 22)

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'scripts/vendor/opencc/STCharacters.txt';
const OUT = 'src/data/glossary/_simplified-only.txt';
const OUT_JA = 'src/data/glossary/_simplified-only-ja.txt';

const keys = new Set();
const traditional = new Set();
for (const line of readFileSync(join(ROOT, SRC), 'utf8').split('\n')) {
  if (!line.trim() || line.startsWith('#')) continue;
  const [key, values = ''] = line.split('\t');
  if ([...key].length !== 1) throw new Error(`${SRC}: unexpected key "${key}"`);
  keys.add(key);
  for (const v of values.trim().split(/\s+/)) if (v) traditional.add(v);
}
const simplifiedOnly = [...keys].filter((ch) => !traditional.has(ch));

// JIS X 0208 kanji: EUC-JP rows 16–84 (lead bytes 0xB0–0xF4) × cells 0xA1–0xFE
const jis = new Set();
const euc = new TextDecoder('euc-jp');
for (let a = 0xb0; a <= 0xf4; a++) for (let b = 0xa1; b <= 0xfe; b++) {
  const ch = euc.decode(Uint8Array.of(a, b));
  if (/^\p{Script=Han}$/u.test(ch)) jis.add(ch);
}
if (jis.size < 6000) throw new Error(`EUC-JP decoder yielded only ${jis.size} kanji: this Node lacks full ICU`);
const simplifiedOnlyJa = simplifiedOnly.filter((ch) => !jis.has(ch));

const sortCp = (a) => a.sort((x, y) => x.codePointAt(0) - y.codePointAt(0));
function write(file, chars, what) {
  const rows = [];
  for (let i = 0; i < chars.length; i += 50) rows.push(chars.slice(i, i + 50).join(''));
  writeFileSync(join(ROOT, file), [
    `# ${what}`,
    `# Generated by scripts/simplified-chars.mjs from ${SRC} (OpenCC, Apache License 2.0: scripts/vendor/opencc/LICENSE).`,
    '# Do not edit by hand. Read by L-13 ④ (src/lib/validate.mjs); # starts a comment, whitespace is ignored.',
    `# ${chars.length} characters, sorted by code point.`,
    ...rows,
    '',
  ].join('\n'));
  console.log(`${file}: ${chars.length} characters`);
}

write(OUT, sortCp(simplifiedOnly), 'Simplified-only characters: not allowed in zh-Hant copy (I18-07).');
write(OUT_JA, sortCp(simplifiedOnlyJa), 'Simplified-only characters outside JIS X 0208: not allowed in ja copy (I18-07).');
console.log(`(OpenCC keys ${keys.size}, traditional forms ${traditional.size}, JIS X 0208 kanji ${jis.size})`);
